[project]
name = 'counter'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.count-token]
path = 'contracts/count-token.clar'
clarity_version = 3
epoch = 3.1

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
